apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "202:f90:2659:47c4:2cb0:5703:db3b:4328"
nodeRegistration:
  kubeletExtraArgs:
  - name: node-ip
    value: "202:f90:2659:47c4:2cb0:5703:db3b:4328"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
controlPlaneEndpoint: "cluster.lan:6443"
networking:
  podSubnet: "fd64:10::/48"
  serviceSubnet: "fd64:20::/108"
