apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "202:30cb:d884:b689:339e:b169:8a1b:a619"
nodeRegistration:
  kubeletExtraArgs:
  - name: node-ip
    value: "202:30cb:d884:b689:339e:b169:8a1b:a619"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
controlPlaneEndpoint: "cluster.lan:6443"
networking:
  podSubnet: "fd64:10::/48"
  serviceSubnet: "fd64:20::/108"
