unqualified-search-registries = []

[[registry]]
prefix = "ghcr.io/distribution/distribution"
location = "ghcr.io/distribution/distribution"

[[registry]]
prefix = "docker.io"
location = "docker.io"

[[registry.mirror]]
location = "192.168.64.64:5000"
insecure = true

[[registry.mirror]]
location = "mirror.gcr.io"

[[registry]]
prefix = "ghcr.io"
location = "ghcr.io"

[[registry.mirror]]
location = "192.168.64.64:5001"
insecure = true

[[registry]]
prefix = "quay.io"
location = "quay.io"

[[registry.mirror]]
location = "192.168.64.64:5002"
insecure = true

[[registry]]
prefix = "registry.k8s.io"
location = "registry.k8s.io"

[[registry.mirror]]
location = "192.168.64.64:5003"
insecure = true
