apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - name: kube-scheduler
    resources:
      limits: null
      requests:
        cpu: 10m
        memory: 10Mi
