- name: static
  hosts: centos, fedora
  tasks:
  - name: configure network
    shell: |
      nmcli connection modify eth0 \
      ipv4.addresses "{{ ip_address }}/24" \
      ipv4.dns 192.168.64.1 ipv4.gateway 192.168.64.1 ipv4.method manual

- name: static
  hosts: debian
  tasks:
  - name: install network manager
    apt:
      name: network-manager
  - name: configure network
    shell: |
      sed -i -e '/eth0/s/^/# /' /etc/network/interfaces
      nmcli connection add type ethernet ifname eth0 con-name eth0 \
      ipv4.addresses "{{ ip_address }}/24" \
      ipv4.dns 192.168.64.1 ipv4.gateway 192.168.64.1 ipv4.method manual

- name: static
  hosts: ubuntu
  tasks:
  - name: configure netplan
    shell: |
      sed -i -e '3i\  renderer: NetworkManager' /etc/netplan/00-installer-config.yaml
      sed -i -e '/dhcp4/s/true/false/' /etc/netplan/00-installer-config.yaml
  - name: install network manager
    apt:
      name: network-manager
  - name: configure network
    shell: |
      nmcli connection modify netplan-eth0 connection.id eth0 \
      ipv4.addresses "{{ ip_address }}/24" \
      ipv4.dns 192.168.64.1 ipv4.gateway 192.168.64.1 ipv4.method manual
  - name: disable systemd-networkd
    systemd_service:
      name: systemd-networkd
      enabled: false
