- name: static
  hosts: centos, fedora
  tasks:
  - name: configure network
    shell: |
      nmcli connection modify enp0s1 ipv4.addresses "{{ ip_address }}/24" \
      ipv4.dns 192.168.64.1 ipv4.gateway 192.168.64.1 ipv4.method manual

- name: static
  hosts: debian
  tasks:
  - name: install network manager
    apt:
      name: network-manager
  - name: configure network
    shell: |
      sed -i '/enp0s1/s/^/# /' /etc/network/interfaces
      nmcli connection add type ethernet ifname enp0s1 con-name enp0s1 \
      ipv4.addresses "{{ ansible_enp0s1.ipv4.address }}/24" \
      ipv4.dns 192.168.64.1 ipv4.gateway 192.168.64.1 ipv4.method manual
  - name: restart network manager
    systemd_service:
      name: NetworkManager
      state: restarted
  - name: enable enp0s1 connection
    command: nmcli connection up enp0s1
  - name: configure network
    shell: |
      nmcli connection modify enp0s1 ipv4.addresses "{{ ip_address }}/24" \
      ipv4.dns 192.168.64.1 ipv4.gateway 192.168.64.1 ipv4.method manual

- name: static
  hosts: ubuntu
  tasks:
  - name: configure netplan
    shell: |
      sed -i -e '3i\  renderer: NetworkManager' /etc/netplan/00-installer-config.yaml
      sed -i -e /dhcp4/s/true/false/ /etc/netplan/00-installer-config.yaml
  - name: install network manager
    apt:
      name: network-manager
  - name: configure network
    shell: |
      nmcli connection modify netplan-enp0s1 connection.id enp0s1 \
      ipv4.addresses "{{ ansible_enp0s1.ipv4.address }}/24" \
      ipv4.dns 192.168.64.1 ipv4.gateway 192.168.64.1 ipv4.method manual
      nmcli connection up enp0s1
  - name: configure network
    shell: |
      nmcli connection modify enp0s1 ipv4.addresses "{{ ip_address }}/24" \
      ipv4.dns 192.168.64.1 ipv4.gateway 192.168.64.1 ipv4.method manual
