- name: update
  hosts: centos, fedora
  tasks:
  - name: update
    shell: |
      dnf -y update
      dnf -y autoremove

- name: update
  hosts: debian, ubuntu
  tasks:
  - name: update
    shell: |
      apt-get -y update
      apt-get -y upgrade
      apt-get -y autoremove
