- name: update
  hosts: centos, fedora
  tasks:
  - name: update
    dnf:
      name: "*"
      state: latest
  - name: autoremove
    dnf:
      autoremove: true

- name: update
  hosts: debian, ubuntu
  tasks:
  - name: update
    apt:
      name: "*"
      state: latest
  - name: autoremove
    apt:
      autoremove: true
